spring.application.name=helpdesk-system

# Datasource
spring.datasource.url=jdbc:postgresql://localhost:5433/helpdesk_db
spring.datasource.username=helpdesk_user
spring.datasource.password=helpdesk_pass
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
# ddl-auto НЕ використовуємо - схемою керує Liquibase
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Liquibase
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml
spring.liquibase.enabled=true

# Thymeleaf
spring.thymeleaf.cache=false

# Security: OIDC (Client) - Keycloak
spring.security.oauth2.client.registration.keycloak.client-id=helpdesk-ui-client
spring.security.oauth2.client.registration.keycloak.client-secret=HMAPXj0OBjE7EO7OmZncKVC0bzVLxzvv
spring.security.oauth2.client.registration.keycloak.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.keycloak.scope=openid,profile,email
spring.security.oauth2.client.registration.keycloak.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}
spring.security.oauth2.client.provider.keycloak.issuer-uri=http://localhost:8080/realms/helpdesk-realm
spring.security.oauth2.client.provider.keycloak.user-name-attribute=preferred_username

# Security: JWT (Resource Server)
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080/realms/helpdesk-realm
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8080/realms/helpdesk-realm/protocol/openid-connect/certs

# Server
server.port=8081

# Logging
logging.level.org.springframework.security=DEBUG
logging.level.liquibase=INFO